### ISSUE TITLE
Create Metadata always needed? 

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/DataHUB#6]
As seen in some user stories, many ARCs fail to succeed at the Metadata creation job when pushing their ARC to the respective Gitlab repository. I want to understand some things about this and wondered:
- why does Metadata creation job always takes place? Wouldn't it be enough to only start it when trying to publish the ARC to Invenio?
- why does Metadata creation job takes place after the Validation? The Validation investigates if the ARC is formally valid but when Metadata creation fails due to, e.g., the Investigation file being incomplete, Validation will never take place, isn't it?
- users get notification emails after every failed job which worries them in return. Is this useful? What about disabling email notification by default and let the user decide if they want to enable them per repo if they want to?

**Comment by kMutagene** [comment]
> why does Metadata creation job takes place after the Validation? The Validation investigates if the ARC is formally valid but when Metadata creation fails due to, e.g., the Investigation file being incomplete, Validation will never take place, isn't it?

This sentence is a bit confusing - but if I understand it right, i agree that validation should take place before metadata creation. It would catch critical errors that prevent metadata creation, and do so in a way more readable way.

> why does Metadata creation job always takes place? Wouldn't it be enough to only start it when trying to publish the ARC to Invenio?

@j-bauer correct me if i am wrong, but I think here, we discussed that the metadata file must always be available, because we cannot trigger (and wait for) any CI jobs to run by starting the publishing process. 

> users get notification emails after every failed job which worries them in return. Is this useful? What about disabling email notification by default and let the user decide if they want to enable them per repo if they want to?

I don't know about this ... If it gets spammy, people can turn it of. I think there is value in receiving notifications about validation errors of arcs.

**Comment by j-bauer** [comment]
Since we are revamping the entire ARC validation pipeline, I'm closing this issue. Let's create new ones for new issues.
